name: CI workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm o

      - name: Run CI checks
        run: npm run ci

      - name: Run changeset
        run: npm run changeset:version

      - name: Commit changeset
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Update package version'
          add: 'package.json yarn.lock .yarn/versions/*'
        
      - name: Push changeset
        uses:
          EndBug/add-and-commit@v7
        with:
          message: 'Update package version'
          add: 'package.json yarn.lock .yarn/versions/*'
          push: true

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: changeset
          title: Update package version
          body: |
            This pull request updates the package version based on the changeset.

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm i

      - name: Build package
        run: npm run build

      - name: Publish package to npm registry
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
        run: npm publish
